using System.Data.SqlClient;
using AcademixPro.Helpers;

namespace AcademixPro.Forms
{
    public class NotificationsControl : UserControl
    {
        private DataGridView dgvNotifications = null!;

        public NotificationsControl()
        {
            Dock = DockStyle.Fill;
            BackColor = AppColors.Background;
            DoubleBuffered = true;
            Load += (_, __) => BuildUI();
        }

        private void BuildUI()
        {
            Controls.Clear();

            // ── Top bar ───────────────────────────────────────────────
            var topPanel = new Panel
            {
                Dock = DockStyle.Top,
                Height = 56,
                BackColor = Color.Transparent,
            };

            var btnRefresh = UIHelper.CreateButton("↻ Refresh", AppColors.SurfaceLight, 110, 36);
            btnRefresh.Location = new Point(0, 10);
            btnRefresh.ForeColor = AppColors.TextSecondary;
            btnRefresh.Click += (_, __) => LoadData();
            topPanel.Controls.Add(btnRefresh);

            var btnMarkRead = UIHelper.CreateButton("✅ Mark as Read", AppColors.Primary, 160, 36);
            btnMarkRead.Location = new Point(120, 10);
            btnMarkRead.Click += BtnMarkRead_Click;
            topPanel.Controls.Add(btnMarkRead);

            var btnSend = UIHelper.CreateButton("📤 Send New", AppColors.CardPurple, 140, 36);
            btnSend.Location = new Point(290, 10);
            btnSend.Click += BtnSend_Click;
            topPanel.Controls.Add(btnSend);

            Controls.Add(topPanel);

            // ── Info label ────────────────────────────────────────────
            var lblInfo = new Label
            {
                Text = "💡 Notifications are also auto-generated by the system when attendance drops below 75%.",
                Font = new Font("Segoe UI", 9.5f),
                ForeColor = AppColors.TextMuted,
                Dock = DockStyle.Top,
                Height = 32,
                BackColor = AppColors.SurfaceLight,
                TextAlign = ContentAlignment.MiddleLeft,
                Padding = new Padding(16, 0, 0, 0),
            };
            Controls.Add(lblInfo);

            // ── Grid ──────────────────────────────────────────────────
            dgvNotifications = new DataGridView { Dock = DockStyle.Fill };
            UIHelper.StyleDataGrid(dgvNotifications);
            Controls.Add(dgvNotifications);

            // Bring top items to front so Dock order is correct
            lblInfo.BringToFront();
            topPanel.BringToFront();

            LoadData();
        }

        private void LoadData()
        {
            dgvNotifications.DataSource = DatabaseHelper.ExecuteQuery(SqlQueries.Notifications.GetUnread);
            if (dgvNotifications.Columns.Contains("NotifID"))
                dgvNotifications.Columns["NotifID"].Visible = false;
            var map = new Dictionary<string, string>
            {
                ["Title"]     = "Title",
                ["Message"]   = "Message",
                ["CreatedAt"] = "Sent At",
            };
            foreach (var kv in map)
                if (dgvNotifications.Columns.Contains(kv.Key))
                    dgvNotifications.Columns[kv.Key].HeaderText = kv.Value;
        }

        private void BtnMarkRead_Click(object? sender, EventArgs e)
        {
            if (dgvNotifications.CurrentRow == null)
            {
                MessageBox.Show("Select a notification first.", "Info",
                    MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }

            int id = Convert.ToInt32(dgvNotifications.CurrentRow.Cells["NotifID"].Value);
            DatabaseHelper.ExecuteNonQuery(SqlQueries.Notifications.MarkRead,
                new[] { new SqlParameter("@NotifID", id) });

            LoadData();
        }

        private void BtnSend_Click(object? sender, EventArgs e)
        {
            // Show a simple dialog to send notification
            using var dlg = new Form
            {
                Text = "Send Notification",
                Size = new Size(440, 320),
                StartPosition = FormStartPosition.CenterParent,
                FormBorderStyle = FormBorderStyle.FixedDialog,
                BackColor = AppColors.Surface,
                MaximizeBox = false,
                MinimizeBox = false,
            };

            var lblTitle = new Label
            {
                Text = "Title",
                Font = new Font("Segoe UI", 9.5f),
                ForeColor = AppColors.TextSecondary,
                Location = new Point(20, 20),
                AutoSize = true,
                BackColor = Color.Transparent,
            };
            dlg.Controls.Add(lblTitle);

            var txtTitle = new TextBox
            {
                Location = new Point(20, 44),
                Size = new Size(380, 30),
            };
            UIHelper.StyleTextBox(txtTitle);
            dlg.Controls.Add(txtTitle);

            var lblMsg = new Label
            {
                Text = "Message",
                Font = new Font("Segoe UI", 9.5f),
                ForeColor = AppColors.TextSecondary,
                Location = new Point(20, 84),
                AutoSize = true,
                BackColor = Color.Transparent,
            };
            dlg.Controls.Add(lblMsg);

            var txtMsg = new TextBox
            {
                Location = new Point(20, 108),
                Size = new Size(380, 80),
                Multiline = true,
            };
            UIHelper.StyleTextBox(txtMsg);
            dlg.Controls.Add(txtMsg);

            var btnOk = UIHelper.CreateButton("📤 Send", AppColors.Primary, 120, 38);
            btnOk.Location = new Point(20, 210);
            btnOk.Click += (_, __) =>
            {
                if (string.IsNullOrWhiteSpace(txtTitle.Text) || string.IsNullOrWhiteSpace(txtMsg.Text))
                {
                    MessageBox.Show("Title and Message are required.");
                    return;
                }

                var parms = new SqlParameter[]
                {
                    new("@UserID", Session.UserID),
                    new("@Title", txtTitle.Text.Trim()),
                    new("@Message", txtMsg.Text.Trim()),
                };

                if (DatabaseHelper.ExecuteNonQuery(SqlQueries.Notifications.Insert, parms) > 0)
                {
                    MessageBox.Show("Notification sent!", "Success",
                        MessageBoxButtons.OK, MessageBoxIcon.Information);
                    dlg.Close();
                }
            };
            dlg.Controls.Add(btnOk);

            var btnCancel = UIHelper.CreateButton("Cancel", AppColors.SurfaceLight, 100, 38);
            btnCancel.ForeColor = AppColors.TextSecondary;
            btnCancel.Location = new Point(150, 210);
            btnCancel.Click += (_, __) => dlg.Close();
            dlg.Controls.Add(btnCancel);

            dlg.ShowDialog();
            LoadData();
        }
    }
}
